### ISSUE TITLE
Can We Please Update the Version Here

### ISSUE THREAD

**Issue by MarcusSorealheis** [cloudant-labs/clouseau#63]
Clouseau is on version 4, but it should be at least on version 8, which will require 3 upgrades because of n-1 index version compatibility guarantees. 

Lucene 9 is much better also: 

`<lucene-version>4.6.1</lucene-version>`

^ This seems a bit negligent. Do you need help with testing or outlining how to upgrade your Clouseau safely?

**Comment by rnewson** [comment]
Hi, we're aware that 4.6.1 is old. We are not updating clouseau to use newer versions of Lucene, that will likely happen in a new project instead. For my part I am working on a replacement here https://github.com/apache/couchdb/pull/429 which uses Lucene 9. The goal is to be able to upgrade between major releases of Lucene by rebuilding, because of the restriction that Lucene X can only read Lucene X-1 indexes.
